### ISSUE TITLE
after 1st mission bot do not send any cargo ships to collect resource

### ISSUE THREAD

**Issue by lintahloo** [Migolina/ikabot#1]
### Bug explanation

aptaloc ilk görevden sonra no cargo ship no loot 2 saat kod yazcan
 if barbarian_resources_juicy ;
send Cargo_ships_to_Carry_juicy_resources_from_barbarian_mommie

### Operating System

win 31

### Ikabot installation

I downloaded the pre-built Windows binary

### Ikabot version

sonuncu işte

### Python version

3.9 bir şey

**Comment by enistaylandurmaz** [comment]
try again

**Comment by lintahloo** [comment]
okay well done my friend it wörks şimdi
